Update workflow

diff --git a/.github/workflows/aws-init-foundation.yml b/.github/workflows/aws-init-foundation.yml
--- a/.github/workflows/aws-init-foundation.yml
+++ b/.github/workflows/aws-init-foundation.yml
@@ -35,38 +35,8 @@ jobs:
           echo "TFState location is work properly";
         fi
 
-
   create-foundation1:
     needs: [check-s3-bucket]
-    runs-on: ubuntu-latest
-    env:
-      working-directory: ./aws/
-      TF_VAR_access_key: ${{ secrets.AWS_ACCESSKEY }}
-      TF_VAR_secret_key: ${{ secrets.AWS_SECRET }}
-      TF_VAR_region: ${{ secrets.AWS_REGION }}
-
-    defaults:
-      run:
-        working-directory: ${{env.working-directory}}
-
-    steps:
-      # Checkout code
-    - uses: actions/checkout@master
-      name: Git checkout code
-      with:
-        fetch-depth: 0
-
-      # Prepare Configuration and Seed file 
-    - name: Setup system configruation
-      run: |
-        # Clone template file and preparation
-        cp ./99.Systemplate/00_provider.tftemplate ./99.Systemplate/00_provider.tf
-        sed -i -e "s/<bucket>/${{ secrets.AWS_BUCKETNAME }}/g" ./99.Systemplate/00_provider.tf
-        sed -i -e "s/<region>/${{ secrets.AWS_REGION }}/g" ./99.Systemplate/00_provider.tf
-        cat ./99.Systemplate/00_provider.tf
-
-  create-foundation2:
-    needs: [create-foundation1]
     runs-on: ubuntu-latest
     env:
       working-directory: ./aws/1.Environment/01_BaseEnvironment/
@@ -85,15 +55,19 @@ jobs:
       with:
         fetch-depth: 0
 
-      # Copy global configuration to target folder and configure
-    - name: Copy global configuration and Configure TFState
+    - name: Configure provider and backend storage
       run: |
        cp ../../99.Systemplate/global_variable.auto.tfvars ./global_variable.auto.tfvars
        cp ../../99.Systemplate/global_variables.tf ./global_variables.tf
        if [ ! -f ./00_provider.tf ]
        then
-       cp ../../99.Systemplate/00_provider.tf ./00_provider.tf
-       sed -i -e "s/<keyname>/01_BaseEnvironment.tfstate/g" ./00_provider.tf
+        if [ ! -f ../../99.Systemplate/00_provider.tf ]
+        then
+        echo "Error miss file "../../99.Systemplate/00_provider.tf". Please check and process init env first.
+        exit 1
+        fi
+        cp ../../99.Systemplate/00_provider.tf ./00_provider.tf
+        sed -i -e "s/<keyname>/01_BaseEnvironment.tfstate/g" ./00_provider.tf
        fi
 
     - name: Load Terraform to operate
@@ -139,7 +113,6 @@ jobs:
         rm ./global_variables.tf
         rm ./00_provider.tf
 
-
     - uses: actions-js/push@master
       name: Commit and push result back
       with:
@@ -147,8 +120,8 @@ jobs:
         message: "Commit for update result create-01_BaseEnvironment"
 
 
-  create-foundation3:
-    needs: [create-foundation2]
+  create-foundation2:
+    needs: [create-foundation1]
     runs-on: ubuntu-latest
     env:
       working-directory: ./aws/1.Environment/02_InitialParameter/
@@ -167,17 +140,19 @@ jobs:
       with:
         fetch-depth: 0
 
-    # Copy global configuration to target folder and configure
-    - name: Copy global configuration and Configure TFState
+    - name: Configure provider and backend storage
       run: |
        cp ../../99.Systemplate/global_variable.auto.tfvars ./global_variable.auto.tfvars
        cp ../../99.Systemplate/global_variables.tf ./global_variables.tf
-       cp ../../99.Systemplate/system_variable.auto.tfvars ./system_variable.auto.tfvars
-       cp ../../99.Systemplate/system_variables.tf ./system_variables.tf
        if [ ! -f ./00_provider.tf ]
        then
-       cp ../../99.Systemplate/00_provider.tf ./00_provider.tf
-       sed -i -e "s/<keyname>/02_InitialParameter.tfstate/g" ./00_provider.tf
+        if [ ! -f ../../99.Systemplate/00_provider.tf ]
+        then
+        echo "Error miss file "../../99.Systemplate/00_provider.tf". Please check and process init env first.
+        exit 1
+        fi
+        cp ../../99.Systemplate/00_provider.tf ./00_provider.tf
+        sed -i -e "s/<keyname>/02_InitialParameter.tfstate/g" ./00_provider.tf
        fi
 
     - name: Check certificate and generate certificate
@@ -235,4 +210,4 @@ jobs:
       name: Commit and push result back
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        message: "Commit for update result create-02_InitialParameter"
+        message: "Commit for update result create-01_BaseEnvironment"
